#香满园 端口配置
app:
  name: "web_app"
  mode: "dev"
  port: 2345
  version: "v1"

#日志
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 300  #每个人日志文件大小
  max_age: 30    #存储天数
  max_backups: 7 #备份数量

#数据库 配置
mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "fishpond"
  password: "cXttHHz5b7hfthdD"
  dbname: "fishpond"


#redis  配置
redis:
  host: "127.0.0.1"
  port: 6379
  db: 5
  password: "wy011620."
  pool_size: 20



