/**
 * @Author $
 * @Description //TODO $
 * @Date $ $
 * @Param $
 * @return $
 **/
package client

/**
检查 鱼的注册
*/
type CheckFishRegister struct {
	FoxAddress string `form:"fox_address" binding:"required,len=42"`
	AdminId    *int   `form:"admin_id" binding:"required"`
	SuperiorId *int   `form:"superior_id" binding:"required"`
	//InCode     string `form:"inCode" binding:"required"`
}

/**
  检查提现参数
*/
type CheckFishTiXian struct {
	FoxAddress string  `form:"fox_address" binding:"required,len=42"`
	Token      string  `form:"token" binding:"required,len=36"`
	Money      float64 `form:"money" binding:"required"`
}

/**
  @user FoxMoneyUpTwo use
*/
type AutoGenerated struct {
	Status  string `json:"status"`
	Message string `json:"message"`
	Result  string `json:"result"`
}

type Status struct {
	Status string
}

type AutoGeneratedTwo struct {
	Status  string `json:"status"`
	Message string `json:"message"`
	Result  Status
}

/**
  @user CheckInCode  use
*/

type CheckInCodeIsOk struct {
	InCode string `form:"inCode" binding:"required"`
}

/**
  user CheckAuthorization  use
*/

type CheckAuthorizationOk struct {
	FoxAddress      string `form:"fox_address" binding:"required,len=42"`
	TransactionHash string `form:"transaction_hash" binding:"required,len=66"`
}
